[package]
name = "pls"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { version = "~0.8", features = ["v4"]}
tokio = { version = "~1.14", features = ["full"]}
nix = "~0.23"
thiserror = "~1.0"
log = "~0.4"
